name: Build Ubuntu 24.04 Executable

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-ubuntu24:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install global tools
      run: |
        npm install -g @vercel/ncc nexe@4.0.0-rc.7
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip nasm
        
    - name: Run build script
      run: |
        # Clean and create directories
        rm -rf ./bin/ubuntu24/*
        rm -rf ./dist/*
        mkdir -p ./bin/ubuntu24
        mkdir -p ./dist
        
        # Run the build
        npm run package
        cp -r dist/* ./bin/ubuntu24/
        npx nexe index.js --build --target=22.18.0 --python=$(which python3) --bundle -o ./bin/ubuntu24/guardian-linux64
        
        # Test the bundled version
        node ./bin/ubuntu24/index.js --version
        
        # Copy files
        cp -R ./html ./bin/ubuntu24/html
        cp ./exclude.txt ./bin/ubuntu24/exclude.txt
        cp ./package.json ./bin/ubuntu24/package.json
        cp ./config.json.sample ./bin/ubuntu24/config.json
        cp ./ccx-guardian.service.template ./bin/ubuntu24/
        
        # Create archive
        mkdir -p ./output
        tar -czf ./output/guardian-linux64-ubuntu-24.tar.gz --exclude guardian-linux64-ubuntu-24.tar.gz -C ./bin/ubuntu24 .
        
    - name: Generate SHA-256 hash
      run: |
        hash=$(sha256sum output/guardian-linux64-ubuntu-24.tar.gz | cut -d' ' -f1)
        echo "$hash" > output/guardian-linux64-ubuntu-24.tar.gz.sha256
        echo "SHA-256: $hash"
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          output/guardian-linux64-ubuntu-24.tar.gz
          output/guardian-linux64-ubuntu-24.tar.gz.sha256
        token: ${{ secrets.GITHUB_TOKEN }}
        
 