name: Build Ubuntu 22.04 Executable

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-ubuntu22]

permissions:
  contents: write

jobs:
  build-ubuntu22:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.client_payload.branch || 'master' }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install global tools
      run: |
        npm install -g @vercel/ncc nexe@4.0.0-rc.7
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip nasm
        
    - name: Run build script
      run: |
        # Clean and create directories
        rm -rf ./bin/ubuntu22/*
        rm -rf ./dist/*
        mkdir -p ./bin/ubuntu22
        mkdir -p ./dist
        
        # Run the build
        npm run package
        cp -r dist/* ./bin/ubuntu22/
        npx nexe index.js --build --target=22.18.0 --python=$(which python3) --bundle -o ./bin/ubuntu22/guardian-linux64
        
        # Test the bundled version
        node ./bin/ubuntu22/index.js --version
        
        # Copy files
        cp -R ./html ./bin/ubuntu22/html
        cp ./exclude.txt ./bin/ubuntu22/exclude.txt
        cp ./package.json ./bin/ubuntu22/package.json
        cp ./config.json.sample ./bin/ubuntu22/config.json
        cp ./ccx-guardian.service.template ./bin/ubuntu22/
        
        mkdir -p ./output
        tar -czf ./output/guardian-linux64-ubuntu-22.tar.gz -C ./bin/ubuntu22 .
        
    - name: Generate SHA-256 hash
      run: |
        hash=$(sha256sum output/guardian-linux64-ubuntu-22.tar.gz | cut -d' ' -f1)
        echo "$hash" > output/guardian-linux64-ubuntu-22.tar.gz.sha256
        echo "SHA-256: $hash"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: guardian-linux64-ubuntu22
        path: output/guardian-linux64-ubuntu-22.tar.gz
        retention-days: 3
        
 