name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Windows Build
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-windows.yml',
            ref: context.ref,
          })
          
    - name: Trigger Ubuntu 22.04 Build
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-ubuntu22.yml',
            ref: context.ref,
          })
          
    - name: Trigger Ubuntu 24.04 Build
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-ubuntu24.yml',
            ref: context.ref,
          })

  wait-for-builds:
    needs: trigger-builds
    runs-on: ubuntu-latest
    steps:
    - name: Wait for builds to complete
      run: |
        echo "Waiting for builds to complete..."
        sleep 300  # Wait 5 minutes for builds to start
        
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: List downloaded artifacts
      run: |
        find artifacts -type f -name "*.zip" -o -name "*.tar.gz" -o -name "*.sha256"
        
    - name: Create Draft Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/guardian-win64/guardian-win64.zip
          artifacts/guardian-win64/guardian-win64.zip.sha256
          artifacts/guardian-linux64-ubuntu22/guardian-linux64-ubuntu-22.tar.gz
          artifacts/guardian-linux64-ubuntu22/guardian-linux64-ubuntu-22.tar.gz.sha256
          artifacts/guardian-linux64-ubuntu24/guardian-linux64-ubuntu-24.tar.gz
          artifacts/guardian-linux64-ubuntu24/guardian-linux64-ubuntu-24.tar.gz.sha256
        draft: true
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }} 

        