name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get version from package.json
      id: version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Check if tag exists
      id: tag_exists
      run: |
        if git ls-remote --tags origin "v${{ steps.version.outputs.version }}" | grep -q "v${{ steps.version.outputs.version }}"; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Tag v${{ steps.version.outputs.version }} already exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Tag v${{ steps.version.outputs.version }} does not exist"
        fi
        
    - name: Create Release Tag
      if: steps.tag_exists.outputs.exists == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v${{ steps.version.outputs.version }}" -m "Release v${{ steps.version.outputs.version }}"
        git push origin "v${{ steps.version.outputs.version }}"
        echo "Created and pushed tag v${{ steps.version.outputs.version }}"
        
    - name: Debug tag info
      run: |
        echo "Current git ref: ${{ github.ref }}"
        echo "Tag name: v${{ steps.version.outputs.version }}"
        git ls-remote --tags origin | grep "v${{ steps.version.outputs.version }}" || echo "Tag not found in remote"
        
    - name: Skip tag creation
      if: steps.tag_exists.outputs.exists == 'true'
      run: |
        echo "Tag v${{ steps.version.outputs.version }} already exists, skipping tag creation"
        
    - name: Check if release exists
      id: release_exists
      run: |
        # Check if a release already exists for this tag
        if curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.version.outputs.version }}" \
          | grep -q '"id"'; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Release for tag v${{ steps.version.outputs.version }} already exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "No release found for tag v${{ steps.version.outputs.version }}"
        fi
        
    - name: Create Draft Release
      if: steps.release_exists.outputs.exists == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ steps.version.outputs.version }}"
        draft: true
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_unmatched_files: false
        generate_release_notes: false
        
    - name: Skip Release Creation
      if: steps.release_exists.outputs.exists == 'true'
      run: |
        echo "Release for tag v${{ steps.version.outputs.version }} already exists, skipping creation"
        
    - name: Trigger Windows Build
      id: windows_build
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: build-windows
        client-payload: '{"release_version": "${{ steps.version.outputs.version }}"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger Ubuntu 22 Build
      id: ubuntu22_build
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: build-ubuntu22
        client-payload: '{"release_version": "${{ steps.version.outputs.version }}"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger Ubuntu 24 Build
      id: ubuntu24_build
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: build-ubuntu24
        client-payload: '{"release_version": "${{ steps.version.outputs.version }}"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Wait for builds to complete
      run: |
        echo "Waiting for builds to complete..."
        echo "Builds can take up to 3hours30, waiting 3 hours 45 to be safe..."
        sleep 13500  # Wait 3.75 hours for builds to complete

    - name: Download all artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: build-windows.yml
        path: windows
        name: guardian-win64
        allow_forks: false

    - name: Download Ubuntu 22 artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: build-ubuntu22.yml
        path: ubuntu22
        name: guardian-linux64-ubuntu22
        allow_forks: false

    - name: Download Ubuntu 24 artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: build-ubuntu24.yml
        path: ubuntu24
        name: guardian-linux64-ubuntu24
        allow_forks: false

    - name: Prepare release files
      run: |
        # List what we actually downloaded
        echo "=== Downloaded artifacts ==="
        ls -la windows/ ubuntu22/ ubuntu24/
        
        # Copy Windows files
        cp windows/guardian-win64.zip .
        cp windows/guardian-win64.zip.sha256 .
        
        # Copy Ubuntu files  
        cp ubuntu22/guardian-linux64-ubuntu-22.tar.gz .
        cp ubuntu22/guardian-linux64-ubuntu-22.tar.gz.sha256 .
        cp ubuntu24/guardian-linux64-ubuntu-24.tar.gz .
        cp ubuntu24/guardian-linux64-ubuntu-24.tar.gz.sha256 .
        
        echo "=== Final files for release ==="
        ls -la *.zip *.tar.gz *.sha256

    - name: Generate checksums for release body
      id: checksums
      run: |
        WINDOWS_CHECKSUM=$(cat guardian-win64.zip.sha256)
        UBUNTU22_CHECKSUM=$(cat guardian-linux64-ubuntu-22.tar.gz.sha256)
        UBUNTU24_CHECKSUM=$(cat guardian-linux64-ubuntu-24.tar.gz.sha256)
        
        echo "windows_checksum=$WINDOWS_CHECKSUM" >> $GITHUB_OUTPUT
        echo "ubuntu22_checksum=$UBUNTU22_CHECKSUM" >> $GITHUB_OUTPUT
        echo "ubuntu24_checksum=$UBUNTU24_CHECKSUM" >> $GITHUB_OUTPUT

    - name: Upload artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ steps.version.outputs.version }}"
        files: |
          guardian-win64.zip
          guardian-linux64-ubuntu-22.tar.gz
          guardian-linux64-ubuntu-24.tar.gz
        body: |
          ## Checksums
          
          **Windows:** guardian-win64.zip sha256
          ```
          ${{ steps.checksums.outputs.windows_checksum }}
          ```
          **Ubuntu 22:** guardian-linux64-ubuntu-22.tar.gz sha256
          ```
          ${{ steps.checksums.outputs.ubuntu22_checksum }}
          ```
          **Ubuntu 24:** guardian-linux64-ubuntu-24.tar.gz sha256
          ```
          ${{ steps.checksums.outputs.ubuntu24_checksum }}
          ```
        append_body: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

        