name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get version from package.json
      id: version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Check if tag exists
      id: tag_exists
      run: |
        if git ls-remote --tags origin "v${{ steps.version.outputs.version }}" | grep -q "v${{ steps.version.outputs.version }}"; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Tag v${{ steps.version.outputs.version }} already exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Tag v${{ steps.version.outputs.version }} does not exist"
        fi
        
    - name: Create Release Tag
      if: steps.tag_exists.outputs.exists == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v${{ steps.version.outputs.version }}" -m "Release v${{ steps.version.outputs.version }}"
        git push origin "v${{ steps.version.outputs.version }}"
        echo "Created and pushed tag v${{ steps.version.outputs.version }}"
        
    - name: Debug tag info
      run: |
        echo "Current git ref: ${{ github.ref }}"
        echo "Tag name: v${{ steps.version.outputs.version }}"
        git ls-remote --tags origin | grep "v${{ steps.version.outputs.version }}" || echo "Tag not found in remote"
        
    - name: Skip tag creation
      if: steps.tag_exists.outputs.exists == 'true'
      run: |
        echo "Tag v${{ steps.version.outputs.version }} already exists, skipping tag creation"
        
    - name: Check if release exists
      id: release_exists
      run: |
        # Check if a release already exists for this tag
        if curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.version.outputs.version }}" \
          | grep -q '"id"'; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Release for tag v${{ steps.version.outputs.version }} already exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "No release found for tag v${{ steps.version.outputs.version }}"
        fi
        
    - name: Create Draft Release
      if: steps.release_exists.outputs.exists == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ steps.version.outputs.version }}"
        draft: true
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_unmatched_files: false
        generate_release_notes: false
        
    - name: Skip Release Creation
      if: steps.release_exists.outputs.exists == 'true'
      run: |
        echo "Release for tag v${{ steps.version.outputs.version }} already exists, skipping creation"
        
    - name: Trigger Windows Build
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: build-windows
        client-payload: '{"release_version": "${{ steps.version.outputs.version }}"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger Ubuntu 22 Build
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: build-ubuntu22
        client-payload: '{"release_version": "${{ steps.version.outputs.version }}"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger Ubuntu 24 Build
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: build-ubuntu24
        client-payload: '{"release_version": "${{ steps.version.outputs.version }}"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Wait for builds to complete
      run: |
        echo "Waiting for builds to complete..."
        echo "Builds can take up to 4 hours, waiting 5 hours to be safe..."
        sleep 18000  # Wait 5 hours for builds to complete
        
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: List downloaded artifacts
      run: |
        find artifacts -type f -name "*.zip" -o -name "*.tar.gz" -o -name "*.sha256"
        
    - name: Upload artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ steps.version.outputs.version }}"
        files: |
          artifacts/guardian-win64/guardian-win64.zip
          artifacts/guardian-win64/guardian-win64.zip.sha256
          artifacts/guardian-linux64-ubuntu22/guardian-linux64-ubuntu-22.tar.gz
          artifacts/guardian-linux64-ubuntu22/guardian-linux64-ubuntu-22.tar.gz.sha256
          artifacts/guardian-linux64-ubuntu24/guardian-linux64-ubuntu-24.tar.gz
          artifacts/guardian-linux64-ubuntu24/guardian-linux64-ubuntu-24.tar.gz.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

        